src/Entity/Salarie.php
<?php

namespace App\Entity;

use App\Repository\SalarieRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SalarieRepository::class)
 */
class Salarie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEmbauche;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="salaries")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    
    public function getDateNaissance()
    {   
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = new DateTime($dateNaissance);

        return $this;
    }

    public function getAnciennete()
    {
        $now = new DateTime();
        $date = date_diff($this->dateEmbauche, $now);
        return $date;
    }

    public function getAge()
    {
        $now = new DateTime();
        $date = date_diff($this->dateNaissance, $now);
        return $date;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDateEmbauche()
    {   
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = new DateTime($dateEmbauche);

        return $this;
    }
    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
}

src/Controller/SalarieController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Entity\Salarie;
use App\Repository\SalarieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/salaries")
 */
class SalarieController extends AbstractController
{
    /**
     * @Route("/add", name="salarie_add")
     * @Route("/{id}/edit", name="salarie_edit")
     */
    public function addSalarie(Salarie $salarie = null, Request $request, EntityManagerInterface $manager){
        if(!$salarie){
            $salarie = new Salarie();
        }

        $form = $this->createFormBuilder($salarie)
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('datenaissance', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('adresse', TextType::class)
            ->add('cp', TextType::class)
            ->add('ville', TextType::class)
            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('Entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'choice_label' => 'raisonSociale',
            ])
            ->add('Valider', SubmitType::class)
            ->getForm();
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $manager->persist($salarie);
            $manager->flush();

            return $this->redirectToRoute('salaries_index');
        }

        return $this->render('salarie/add_edit.html.twig', [
            'form' => $form->createView(),
            'editMode' => $salarie->getId() !== null
        ]);

    }

    /**
     * @Route("/delete/{id}", name="salarie_del")
     */
    public function delSalarie(Salarie $salarie = null, EntityManagerInterface $em) : Response
    {
        if($salarie) {
            $em->remove($salarie);
            $em->flush();
        }
        return $this->redirectToRoute("salaries_index");
    }

    /**
     * @Route("/", name="salaries_index")
     */
    public function index(SalarieRepository $repo): Response
    {
                $salaries = $repo->getAll();

        return $this->render('salarie/index.html.twig', [
            'salaries' => $salaries,
        ]);
    }

    /**
     * @Route("/{id}", name="salarie_show", methods="GET")
     */
    public function show(Salarie $salarie): Response {
        return $this->render('salarie/show.html.twig', ['salarie' => $salarie]);
    }


}

templates/salarie/add_edit.html.twig
{% extends "base.html.twig" %}

{% block contenu %}
    {% if editMode %}
        <h1>Modification</h1>
    {% else %}
        <h1>Ajout</h1>
    {% endif %}

    {{form(form)}}    
{% endblock  %}

templates/salarie/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href={{ asset('css/salarie.css')}}>
{% endblock %}

{% block contenu %}
    <div class="table-responsive">
        <table class="table table-striped" >
            <thead>
                <tr>
                    <th>SALARIE</th>
                    <th>ADRESSE</th>
                    <th>CP</th>
                    <th>VILLE</th>
                    <th>DATE EMBAUCHE</th>
                    <th>ENTREPRISE</th>
                    <th>MODIFIER</th>
                    <th>SUPPRIMER</th>
                </tr>
            </thead>
            <tbody>
                {% for salarie in salaries %}
                    <tr>
                        <td><a href="{{ path('salarie_show', {'id':salarie.id}) }}">{{ salarie.nom ~ ' ' ~ salarie.prenom }}</a></td>
                        <td>{{ salarie.adresse }}</td>
                        <td>{{ salarie.cp }}</td>
                        <td>{{ salarie.ville }}</td>
                        <td>{{ salarie.dateEmbauche | date('d/m/Y') }}</td>
                        <td>{{ salarie.entreprise.raisonSociale }}</td>
                        <td><a href="{{ path('salarie_edit', {'id': salarie.id}) }}"><button class="btn shadow-1 rounded-1 btn-outline btn-opening text-orange"><span class="btn-outline-text">Modifier</span></button></a></td>
                        <td><a href="{{ path('salarie_del', {'id': salarie.id}) }}"><button class="btn shadow-1 rounded-1 btn-outline btn-opening text-red"><span class="btn-outline-text">Supprimer</span></button></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <a href="{{ path('salarie_add') }}"><button class="btn small  shadow-1 rounded-1 btn-outline btn-opening text-green"><span class="btn-outline-text">Ajouter un salarié</span></button></a>
    
{% endblock %}

templates/salarie/show.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    <link rel="stylesheet" href={{ asset('css/salarie.css')}}>
{% endblock %}
{% block contenu %}
<h1>{{ salarie.nom ~ ' ' ~ salarie.prenom }}</h1>
<a href="/salaries"><button class="btn shadow-1 rounded-1 btn-outline btn-opening">Retour à la liste</button></a>
<h4>Date de naissance : {{ salarie.dateNaissance|date('d-m-Y')}} ({{ salarie.age.y }} ans)</h4>
            <h5><pre>Adresse : {{salarie.adresse}} 
          {{salarie.cp}}  {{salarie.ville}} </pre></h5>
<h4>Travail chez : {{ salarie.entreprise.raisonSociale }}</h4>
<h5>Depuis le : {{ salarie.dateEmbauche|date('d-m-Y') }} ({{ salarie.anciennete.y}} ans) </h5>
<a href="{{ path('salarie_edit', {'id': salarie.id}) }}"><button class="btn shadow-1 rounded-1 btn-outline btn-opening text-orange"><span class="btn-outline-text">Modifier</span></button></a>
<a href="{{ path('salarie_del', {'id': salarie.id}) }}"><button class="btn shadow-1 rounded-1 btn-outline btn-opening text-red"><span class="btn-outline-text">Supprimer</span></button></a>
{% endblock %}